--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -104,4 +104,4 @@
         uses: actions/upload-artifact@v4
         with:
           name: prnumber
-          path: ./prnumber.txt
+          path: ./prnumber.txt